/*
*聊天记录
*/
CREATE TABLE `send20140101` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`sender` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'sender',
	`recver` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'recv',
	`smsid` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'smsid',
	`text` VARCHAR(5000) NOT NULL DEFAULT '' COMMENT 'text' COLLATE 'utf8mb4_bin',
	`texttype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'text type TEXT = 1, IMAGE = 2',
	`chattype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'chat type NORMAL = 1, SYSTEM = 2, READSTATE = 3',
	`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'time',
	PRIMARY KEY (`id`)
)COMMENT='log' COLLATE='utf8mb4_bin' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE `send20140102` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`sender` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'sender',
	`recver` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'recv',
	`smsid` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'smsid',
	`text` VARCHAR(5000) NOT NULL DEFAULT '' COMMENT 'text' COLLATE 'utf8mb4_bin',
	`texttype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'text type TEXT = 1, IMAGE = 2',
	`chattype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'chat type NORMAL = 1, SYSTEM = 2, READSTATE = 3',
	`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'time',
	PRIMARY KEY (`id`)
)COMMENT='log' COLLATE='utf8mb4_bin' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE `send20140103` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`sender` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'sender',
	`recver` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'recv',
	`smsid` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'smsid',
	`text` VARCHAR(5000) NOT NULL DEFAULT '' COMMENT 'text' COLLATE 'utf8mb4_bin',
	`texttype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'text type TEXT = 1, IMAGE = 2',
	`chattype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'chat type NORMAL = 1, SYSTEM = 2, READSTATE = 3',
	`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'time',
	PRIMARY KEY (`id`)
)COMMENT='log' COLLATE='utf8mb4_bin' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE `send20140104` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`sender` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'sender',
	`recver` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'recv',
	`smsid` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'smsid',
	`text` VARCHAR(5000) NOT NULL DEFAULT '' COMMENT 'text' COLLATE 'utf8mb4_bin',
	`texttype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'text type TEXT = 1, IMAGE = 2',
	`chattype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'chat type NORMAL = 1, SYSTEM = 2, READSTATE = 3',
	`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'time',
	PRIMARY KEY (`id`)
)COMMENT='log' COLLATE='utf8mb4_bin' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE `send20140105` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`sender` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'sender',
	`recver` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'recv',
	`smsid` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'smsid',
	`text` VARCHAR(5000) NOT NULL DEFAULT '' COMMENT 'text' COLLATE 'utf8mb4_bin',
	`texttype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'text type TEXT = 1, IMAGE = 2',
	`chattype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'chat type NORMAL = 1, SYSTEM = 2, READSTATE = 3',
	`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'time',
	PRIMARY KEY (`id`)
)COMMENT='log' COLLATE='utf8mb4_bin' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE `send20140106` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`sender` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'sender',
	`recver` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'recv',
	`smsid` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'smsid',
	`text` VARCHAR(5000) NOT NULL DEFAULT '' COMMENT 'text' COLLATE 'utf8mb4_bin',
	`texttype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'text type TEXT = 1, IMAGE = 2',
	`chattype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'chat type NORMAL = 1, SYSTEM = 2, READSTATE = 3',
	`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'time',
	PRIMARY KEY (`id`)
)COMMENT='log' COLLATE='utf8mb4_bin' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE `send20140107` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`sender` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'sender',
	`recver` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'recv',
	`smsid` BIGINT(20) NOT NULL DEFAULT '0' COMMENT 'smsid',
	`text` VARCHAR(5000) NOT NULL DEFAULT '' COMMENT 'text' COLLATE 'utf8mb4_bin',
	`texttype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'text type TEXT = 1, IMAGE = 2',
	`chattype` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'chat type NORMAL = 1, SYSTEM = 2, READSTATE = 3',
	`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'time',
	PRIMARY KEY (`id`)
)COMMENT='log' COLLATE='utf8mb4_bin' ENGINE=InnoDB AUTO_INCREMENT=1;
